---
title: "data_wrangling_ii"
output: github_document
date: "2023-10-15"
---

```{r}
library(tidyverse)
library(rvest)
library(httr)

```

Getting data from web to R:
Import NSDUH data
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = 
  read_html(nsduh_url)
```

```{r}
marj_use_df = 
  nsduh_html |> 
  html_table() |> 
  first() |> #takes first element in a list of things (asks for first of 15 tables)
  slice(-1) #remove first row (note) that is not part of data
```


Import star wars …
```{r}
swm_url = 
  "https://www.imdb.com/list/ls070150896/"

swm_html = 
  read_html(swm_url)
```

Using selector gadget...
```{r}
swm_title_vec = 
  swm_html |> 
  html_elements(".lister-item-header a") |> 
  html_text() #takes the stuff out of the html

swm_gross_rev_vec = 
  swm_html |> 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |> 
  html_text()
 
# Create dataframe with what we extracted from html sites
swm_df = 
  tibble(title = swm_title_vec,
         gross_rev = swm_gross_rev_vec)
```


## APIs
Get water data from NYC.
```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```


BRFSS Data
```{r}
brfss_df = 
  GET(
    "https://data.cdc.gov/resource/acme-vg9e.csv",
    query = list("$limit" = 5000)) |> #asking for increased limit
  content()
```



```{r}
#pokemon dataframe
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```



